---

- hosts: machine2
  become: yes
  vars_files:
    - newvar.yml  
vars:
    - var1: variable1
    - var2: variable2
  vars_prompt:
        - name: var3
          prompt: "enter the user name to create"
  tasks: 
    - name: task1
      shell: echo '{{ var1 }}' > /home/ansible/variable.txt
    - name: file
      file: path='/home/ansible/{{var1}}.txt' state=touch
    - name: create user
      user: name='{{ var5 }}' state=present

